In [47]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5' ]
array_list = np.array(object = list_)

# 1

### Yes, The data type of 'list_' is 'list' and 'array_list' is 'numpy.ndarray'.
### We, can print the data type of these by using type() method

In [52]:
list_

['1', '2', '3', '4', '5']

In [51]:
print(f'Data Type of list_: {type(list_)}')

Data Type of list_: <class 'list'>


In [53]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [50]:
print(f'Data Type of array_list: {type(array_list)}')

Data Type of array_list: <class 'numpy.ndarray'>


# 2

In [55]:
list_

['1', '2', '3', '4', '5']

In [62]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [63]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [64]:
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


# 3

In [66]:
array_list = np.array(object = list_, dtype = int)

In [68]:
array_list

array([1, 2, 3, 4, 5])

In [70]:
list_

['1', '2', '3', '4', '5']

### The data type of each element in  'list_' is 'str' but now, data type of each element in 'array_list' is 'numpy.int64'.

In [73]:
for i in list_:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [75]:
for i in array_list:
    print(type(i))

<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [76]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

# 4

In [78]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
# (i) printing the shape of num_array
num_array.shape

(2, 3)

In [85]:
# (ii) printing the size of num_array
num_array.size

6

# 5
### creating a (3x3) zero matrix

In [112]:
import numpy as np

In [117]:
np.zeros(shape = (3,3), dtype = int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

# 6
### creating a (5x5) identity matrix

In [119]:
import numpy as np

In [126]:
np.identity(5, dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])