# `Part 1: Theoretical Questions`

# Q1. What are the different data structures used in Tensorflow?. Give some examples.
___
## `TensorFlow, being a powerful deep learning framework, uses several data structures to represent and manipulate data efficiently`. Some of the common data structures used in TensorFlow are:

## 1. `Tensor`: Tensors are the primary data structures in TensorFlow, representing multi-dimensional arrays. They can have different ranks (number of dimensions) and data types. Tensors are used to store and process the input data, intermediate values, and model parameters. Examples of tensors include scalars (rank 0), vectors (rank 1), matrices (rank 2), and higher-dimensional arrays (rank > 2).

## 2.`tf.constant`: A constant tensor is an immutable tensor with a fixed value that does not change during the course of the computation. It is created using the `tf.constant` function and can be used to hold fixed values like hyperparameters or numerical constants.

### *Example:*
```python
import tensorflow as tf

# Create a constant tensor
tensor_const = tf.constant([1, 2, 3, 4])
```

## 3.`tf.Variable`: A variable tensor is a mutable tensor that can change during the course of the computation. It is used to hold model parameters that need to be updated during training. Variables are created using the `tf.Variable` class.

### *Example:*
```python
import tensorflow as tf

# Create a variable tensor
initial_value = tf.random.normal(shape=(3, 3))
tensor_variable = tf.Variable(initial_value)
```

## 4. `tf.placeholder`: In older versions of TensorFlow, `tf.placeholder` was used to create tensors that act as placeholders for input data during the graph construction phase. However, in recent versions, eager execution is the default mode, and `tf.placeholder` is no longer needed. Instead, you can use Python variables directly in the computation.

### *Example (Older versions)*:
```python
import tensorflow as tf

# Create a placeholder tensor
input_data = tf.placeholder(tf.float32, shape=(None, 784))
```

## 5. `tf.data.Dataset`: The `tf.data.Dataset` API provides a powerful data pipeline for efficiently reading and preprocessing data for training or inference. It allows you to create a dataset from various sources, apply transformations, and iterate through batches during training.

### *Example:*
```python
import tensorflow as tf

# Create a dataset from a numpy array
data = tf.data.Dataset.from_tensor_slices(np.array([1, 2, 3, 4, 5]))

# Apply transformations
data = data.map(lambda x: x * 2).shuffle(buffer_size=5).batch(2)

# Iterate through the dataset
for batch in data:
    print(batch)
```

## *These are some of the common data structures used in TensorFlow, and they play a crucial role in defining the computation graph and efficiently managing data in deep learning models.*

# Q2. How does the TensorFlow constant differ from a TensorFlow variable? Explain with an example.
___
## In TensorFlow, both constants and variables are used to store data in tensors. However, there are some key differences between them:

## 1.`Immutability vs. Mutability`:
   - ## `Constants`: Constants are immutable, which means their values cannot be changed after they are initialized. They are typically used to hold fixed values like hyperparameters or numerical constants.
   - ## `Variables`: Variables, on the other hand, are mutable, which means their values can be updated during the course of the computation. They are typically used to hold model parameters that need to be learned and updated during training.

## 2. `Initialization`:
   - ## `Constants`: Constants are initialized with a fixed value at the time of creation using the `tf.constant` function.
   - ## `Variables`: Variables require an initial value to be provided when they are created. The initial value can be a constant tensor, a random tensor, or even another variable.

### Here's an example to illustrate the difference between a TensorFlow constant and a TensorFlow variable:

In [1]:
import tensorflow as tf

# Create a TensorFlow constant
tensor_const = tf.constant([1, 2, 3, 4])

# Create a TensorFlow variable with an initial value
initial_value = tf.random.normal(shape=(3, 3))
tensor_variable = tf.Variable(initial_value)

In [2]:
tensor_const

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [3]:
tensor_variable

<tf.Variable 'Variable:0' shape=(3, 3) dtype=float32, numpy=
array([[ 0.20427597,  1.0691606 , -0.78566426],
       [-0.7761255 , -0.6040877 , -0.8292028 ],
       [-0.12120707, -0.7888299 ,  0.19783275]], dtype=float32)>

## *In this example, `tensor_const` is a TensorFlow constant, and its value is fixed to `[1, 2, 3, 4]`. It cannot be modified later in the computation.*

## *On the other hand, `tensor_variable` is a TensorFlow variable. It is initialized with a random tensor of shape `(3, 3)` and can be updated during training if needed. For example, we can use gradient descent or other optimization algorithms to update the value of `tensor_variable` during the training process.*

# Q3. Describe the process of matrix addition, multiplication, and element-wise operations in TensorFlow.
___
## In TensorFlow, matrix addition, multiplication, and element-wise operations can be performed using various functions and operators. Let's describe each operation:

## 1. `Matrix Addition`:
   - ## Matrix addition is performed using the `tf.add()` function or the `+` operator. The two matrices being added must have the same shape.

In [4]:
import tensorflow as tf
# Defining two matrices
matrix_a = tf.constant([[1, 2], [3, 4]])
matrix_b = tf.constant([[5, 6], [7, 8]])

In [5]:
print(matrix_a)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [6]:
print(matrix_b)

tf.Tensor(
[[5 6]
 [7 8]], shape=(2, 2), dtype=int32)


In [7]:
# Matrix addition (using tf.add)
tf.add(matrix_a,matrix_b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  8],
       [10, 12]])>

In [8]:
# Matrix addition (using +)
matrix_a + matrix_b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  8],
       [10, 12]])>

## 2. Matrix Multiplication:
   - ## Matrix multiplication is performed using the `tf.matmul()` function or the `@` operator. For element-wise multiplication, we can use the `tf.multiply()` function or the `*` operator.

In [9]:
matrix_a,matrix_b

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[5, 6],
        [7, 8]])>)

In [10]:
# Matrix multiplication (using tf.matmul)
tf.matmul(matrix_a,matrix_b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]])>

In [11]:
# Matrix multiplication (using @)
matrix_a @ matrix_b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[19, 22],
       [43, 50]])>

In [12]:
# Matrix element-wie multiplication (using tf.multiply)
tf.multiply(matrix_a,matrix_b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]])>

In [13]:
# Matrix element-wise multiplication (using *)
matrix_a * matrix_b

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]])>

## 3. Element-wise Operations:
   - ## Element-wise operations apply an operation between corresponding elements of two tensors (matrices) with the same shape. For example, we can use the `tf.add()`, `tf.subtract()`, `tf.multiply()`, `tf.divide()`, and other functions for element-wise operations.

In [14]:
matrix_a,matrix_b

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]])>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[5, 6],
        [7, 8]])>)

In [15]:
# Element-wise addition (using tf.add or +)
tf.add(matrix_a,matrix_b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  8],
       [10, 12]])>

In [16]:
# Element-wise subtraction (using tf.subtract or -)
tf.subtract(matrix_a,matrix_b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-4, -4],
       [-4, -4]])>

In [17]:
# Element-wise multiplicaiton (using tf.multiply or *)
tf.multiply(matrix_a,matrix_b)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 12],
       [21, 32]])>

In [23]:
# Element-wise addition (using tf.divide or /)
tf.divide(matrix_a,matrix_b)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])>

### `Note`: When performing matrix multiplication using `tf.matmul()`, ensure that the shapes of the matrices are compatible for multiplication (i.e., the number of columns in the first matrix must be equal to the number of rows in the second matrix). For element-wise operations, the shapes of the input tensors must be the same.

# `Part 2: Practical Implementation`

># **Task 1: Creating and Manipulating Matrices**

In [19]:
import tensorflow as tf

# Q1. Create a normal matrix A with dimensions 3x3, using TensorFlow's random_normal function. Display the values of matrix A.
___


In [40]:
matrix_A = tf.random.normal(shape=(3,3))

In [41]:
matrix_A.numpy()

array([[ 0.19708003,  0.7502121 , -0.18231754],
       [-0.7191529 , -0.2666759 ,  1.1476651 ],
       [-0.60042775, -1.373721  , -0.81151265]], dtype=float32)

# Q2. Create a Gaussian matrix B with dimensions 3x3, using TensorFlow's truncated_normal function. Display the values of matrix B.
___

In [46]:
matrix_B = tf.random.truncated_normal(shape=(3,3))

In [47]:
matrix_B.numpy()

array([[-1.6304157 , -0.46560797, -0.6696561 ],
       [ 0.7305882 , -0.8702906 ,  0.96658623],
       [ 0.5249548 , -0.44582632, -1.0809076 ]], dtype=float32)

# Q3. Create a matrix C with dimensions 2x3, where the values are drawn from a normal distribution with a mean of 3 and a standard deviation of 0.5, using TensorFlow's random.normal function. Display the values of matrix C.
___

In [53]:
matrix_C = tf.random.normal(shape=(2,3),mean = 3, stddev=0.5)

In [54]:
matrix_C.numpy()

array([[3.1724694, 2.24002  , 2.777005 ],
       [2.7108805, 2.8456235, 2.3292804]], dtype=float32)

# Q4. Perform matrix addition between matrix A and matrix B, and store the result in matrix D.
___

In [57]:
matrix_A.numpy()

array([[ 0.19708003,  0.7502121 , -0.18231754],
       [-0.7191529 , -0.2666759 ,  1.1476651 ],
       [-0.60042775, -1.373721  , -0.81151265]], dtype=float32)

In [58]:
matrix_B.numpy()

array([[-1.6304157 , -0.46560797, -0.6696561 ],
       [ 0.7305882 , -0.8702906 ,  0.96658623],
       [ 0.5249548 , -0.44582632, -1.0809076 ]], dtype=float32)

In [50]:
matrix_D = tf.add(matrix_A,matrix_B)

In [51]:
matrix_D.numpy()

array([[-1.4333357 ,  0.2846041 , -0.85197365],
       [ 0.01143527, -1.1369665 ,  2.1142514 ],
       [-0.07547295, -1.8195473 , -1.8924203 ]], dtype=float32)

# Q5. Perform matrix multiplication between matrix C and matrix D, and store the result in matrix E.
___

In [59]:
matrix_C.numpy()

array([[3.1724694, 2.24002  , 2.777005 ],
       [2.7108805, 2.8456235, 2.3292804]], dtype=float32)

In [60]:
matrix_D.numpy()

array([[-1.4333357 ,  0.2846041 , -0.85197365],
       [ 0.01143527, -1.1369665 ,  2.1142514 ],
       [-0.07547295, -1.8195473 , -1.8924203 ]], dtype=float32)

In [61]:
matrix_E = tf.matmul(matrix_C,matrix_D)

In [62]:
matrix_E

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-4.731187  , -6.6968217 , -3.2221553 ],
       [-4.0288587 , -6.7020864 , -0.70121276]], dtype=float32)>

># **Task 2: Performing Additional Matrix Operations**

In [65]:
import tensorflow as tf

# Q1. Create a matrix F with dimensions 3x3, initialized with random values using TensorFlow's random_uniform function.
___

In [95]:
matrix_F = tf.random.uniform(shape=(3,3))

In [101]:
matrix_F.numpy()

array([[0.53619456, 0.5416889 , 0.45589566],
       [0.4438113 , 0.39252293, 0.92210793],
       [0.20408809, 0.04513919, 0.7531333 ]], dtype=float32)

# Q2. Calculate the transpose of matrix F and store the result in matrix G.
___

In [97]:
matrix_G = tf.transpose(matrix_F)

In [102]:
matrix_G.numpy()

array([[0.53619456, 0.4438113 , 0.20408809],
       [0.5416889 , 0.39252293, 0.04513919],
       [0.45589566, 0.92210793, 0.7531333 ]], dtype=float32)

# Q3.Calculate the element-wise exponential of matrix F and store the result in matrix H.
___

In [99]:
matrix_H = tf.exp(matrix_F)

In [100]:
matrix_H.numpy()

array([[1.7094891, 1.7189075, 1.5775857],
       [1.5586363, 1.4807118, 2.5145855],
       [1.2264062, 1.0461735, 2.1236436]], dtype=float32)

# Q4. Create a matrix I by concatenating matrix F and matrix G horizontally.
___

In [110]:
matrix_F.numpy()

array([[0.53619456, 0.5416889 , 0.45589566],
       [0.4438113 , 0.39252293, 0.92210793],
       [0.20408809, 0.04513919, 0.7531333 ]], dtype=float32)

In [109]:
matrix_G.numpy()

array([[0.53619456, 0.4438113 , 0.20408809],
       [0.5416889 , 0.39252293, 0.04513919],
       [0.45589566, 0.92210793, 0.7531333 ]], dtype=float32)

In [106]:
matrix_I = tf.concat([matrix_F,matrix_G],1)

In [107]:
matrix_I.numpy()

array([[0.53619456, 0.5416889 , 0.45589566, 0.53619456, 0.4438113 ,
        0.20408809],
       [0.4438113 , 0.39252293, 0.92210793, 0.5416889 , 0.39252293,
        0.04513919],
       [0.20408809, 0.04513919, 0.7531333 , 0.45589566, 0.92210793,
        0.7531333 ]], dtype=float32)

# Q5. Create a matrix J by concatenating matrix F and matrix H vertically.
___

In [111]:
matrix_F.numpy()

array([[0.53619456, 0.5416889 , 0.45589566],
       [0.4438113 , 0.39252293, 0.92210793],
       [0.20408809, 0.04513919, 0.7531333 ]], dtype=float32)

In [112]:
matrix_H.numpy()

array([[1.7094891, 1.7189075, 1.5775857],
       [1.5586363, 1.4807118, 2.5145855],
       [1.2264062, 1.0461735, 2.1236436]], dtype=float32)

In [113]:
matrix_J = tf.concat([matrix_F,matrix_H],0)

In [114]:
matrix_J.numpy()

array([[0.53619456, 0.5416889 , 0.45589566],
       [0.4438113 , 0.39252293, 0.92210793],
       [0.20408809, 0.04513919, 0.7531333 ],
       [1.7094891 , 1.7189075 , 1.5775857 ],
       [1.5586363 , 1.4807118 , 2.5145855 ],
       [1.2264062 , 1.0461735 , 2.1236436 ]], dtype=float32)